// <auto-generated />
using System;
using FloraLink.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloraLink.Migrations
{
    [DbContext(typeof(FloraLinkDbContext))]
    partial class FloraLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloraLink.Domain.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.PlantDiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantDiaryEntries");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.PlantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CriticalMoistureThreshold")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxMoisture")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double>("MinMoisture")
                        .HasColumnType("float");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlantTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriticalMoistureThreshold = 10.0,
                            Description = "Desert succulent, very drought tolerant",
                            MaxMoisture = 40.0,
                            MaxTemperature = 35.0,
                            MinMoisture = 20.0,
                            MinTemperature = 20.0,
                            Name = "Cactus"
                        },
                        new
                        {
                            Id = 2,
                            CriticalMoistureThreshold = 40.0,
                            Description = "Tropical plants needing high humidity",
                            MaxMoisture = 80.0,
                            MaxTemperature = 30.0,
                            MinMoisture = 60.0,
                            MinTemperature = 18.0,
                            Name = "Tropical"
                        },
                        new
                        {
                            Id = 3,
                            CriticalMoistureThreshold = 30.0,
                            Description = "Kitchen herbs like basil and mint",
                            MaxMoisture = 70.0,
                            MaxTemperature = 28.0,
                            MinMoisture = 50.0,
                            MinTemperature = 15.0,
                            Name = "Herb"
                        },
                        new
                        {
                            Id = 4,
                            CriticalMoistureThreshold = 50.0,
                            Description = "Shade-loving moisture-hungry ferns",
                            MaxMoisture = 90.0,
                            MaxTemperature = 25.0,
                            MinMoisture = 70.0,
                            MinTemperature = 15.0,
                            Name = "Fern"
                        },
                        new
                        {
                            Id = 5,
                            CriticalMoistureThreshold = 15.0,
                            Description = "Drought-tolerant succulent plants",
                            MaxMoisture = 50.0,
                            MaxTemperature = 32.0,
                            MinMoisture = 25.0,
                            MinTemperature = 15.0,
                            Name = "Succulent"
                        });
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("HealthScore")
                        .HasColumnType("float");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("PlantStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("SoilMoisture")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.WateringEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<double>("WaterAmountMl")
                        .HasColumnType("float");

                    b.Property<DateTime>("WateredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("WateringEvents");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.Alert", b =>
                {
                    b.HasOne("FloraLink.Domain.Entities.Plant", "Plant")
                        .WithMany("Alerts")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.Plant", b =>
                {
                    b.HasOne("FloraLink.Domain.Entities.PlantType", "PlantType")
                        .WithMany("Plants")
                        .HasForeignKey("PlantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloraLink.Domain.Entities.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.PlantDiaryEntry", b =>
                {
                    b.HasOne("FloraLink.Domain.Entities.Plant", "Plant")
                        .WithMany("DiaryEntries")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("FloraLink.Domain.Entities.Plant", "Plant")
                        .WithMany("SensorReadings")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.WateringEvent", b =>
                {
                    b.HasOne("FloraLink.Domain.Entities.Plant", "Plant")
                        .WithMany("WateringEvents")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.Plant", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("DiaryEntries");

                    b.Navigation("SensorReadings");

                    b.Navigation("WateringEvents");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.PlantType", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("FloraLink.Domain.Entities.User", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
